- name: Create PK3 file
  run: |
    short=$(git rev-parse --short HEAD)
    zip -r LithiumCore.pk3 * -x ".git*" -x ".github/*" -x "output/*"
    cp LithiumCore.pk3 "LithiumCore_${short}.pk3"

- name: Upload PK3 artifact
  uses: actions/upload-artifact@v4
  with:
    name: LithiumCore
    path: |
      LithiumCore.pk3
      LithiumCore_*.pk3
